services:
  - type: web
    name: todoproject
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn todoproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todoproject-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: todoproject-db
    databaseName: todoproject
    user: todouser
